package com.QMPotentialTest;

import com.CapstonePhys.QMPotentialTest.R;
import com.QMPotentialTest.GaussianPotential;
import com.jjoe64.graphview.GraphView;
import com.jjoe64.graphview.LineGraphView;
import com.jjoe64.graphview.GraphView.*;


import android.app.Activity;
import android.os.Bundle;
import android.graphics.Color;
import android.widget.LinearLayout;
import android.widget.SeekBar;
import android.widget.TextView;

import java.text.DecimalFormat;
import java.text.NumberFormat;

public class QMPotentialActivity extends Activity{
	//Global objects/variables
    //Hardcoded initial Kappa and alpha for now:
    final double INITKAPPA = 1;
    final double INITALPHA = 1.5;
    NumberFormat formatter = new DecimalFormat("#0.000");
    
	GaussianPotential gp = new GaussianPotential(INITKAPPA, INITALPHA); 
	
	GraphViewSeries vSeries;
	GraphViewSeries psiSeries;
	
	
    /** Called when the activity is first created. */
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.main);
        
        SeekBar kappaSeekBar;
        
        makePlot();
        
        kappaSeekBar = (SeekBar) findViewById(R.id.kappabar);
        kappaSeekBar.setMax(500);
        kappaSeekBar.setOnSeekBarChangeListener( 
        		new SeekBar.OnSeekBarChangeListener() {
					
					@Override
					public void onStopTrackingTouch(SeekBar seekBar) {
						// TODO Auto-generated method stub
						System.out.println("onStopTracking");
					}
					
					@Override
					public void onStartTrackingTouch(SeekBar seekBar) {
						// TODO Auto-generated method stub
						System.out.println("onStartTracking");
					}
					
					@Override
					public void onProgressChanged(SeekBar seekBar, int progress,
							boolean fromUser) {
						// TODO Auto-generated method stub
						System.out.println(".3: Start onProgress..");
						System.out.println("Progress: " + progress);
						gp.setKappa((double) progress/100); //Progress out of 500
						refreshPlot();
						System.out.println("4: Finish onProgress");
					}
				});
				
    }
    /**
     * Function used to refresh the plot each time for new values of kappa and alpha. 
     */
    public void makePlot(){
        //Getting GaussianPotential data
    	gp.initValues();
    	gp.integrateFun();
    	double Transmitted = gp.getT();
    	double Reflected = 1-Transmitted;      //Reflected so we don't overwrite the 
    										   //special autogenerated R files
    	System.out.println("Kappa = "+ gp.getKappa());
    	vSeries = getPotential();
    	psiSeries = getData();
    	GraphView firstgraphView = new LineGraphView(  
    			this, // context  
    			"T: "+formatter.format(Transmitted)+
    			"     R: "+formatter.format(Reflected)  //Format the decimals to *.*** format.
    			); 
    	((LineGraphView) firstgraphView).setDrawBackground(true);
    	firstgraphView.addSeries(psiSeries); // Add Psi data
    	firstgraphView.addSeries(vSeries);   // Add V(x) data
        
        
     // set view port, start=-5, size=10  
        //graphView.setViewPort(-5, 10);
        firstgraphView.setScrollable(false);  
        // optional - activate scaling / zooming  
        firstgraphView.setScalable(false); 

        LinearLayout layout = (LinearLayout) findViewById(R.id.llplot);
        layout.addView(firstgraphView);
    }
    /**
     * Refreshing the plot
     */
    public void refreshPlot(){
    	//clearing old series:
//    	graphView.removeSeries(psiSeries); //OK so we can't do this with graphView not an attribute.
//    	graphView.removeSeries(vSeries);
    	
        //Getting GaussianPotential data
    	gp.initValues();
    	gp.integrateFun();
    	double Transmitted = gp.getT();
    	double Reflected = 1-Transmitted;      //Reflected so we don't overwrite the 
    										   //special autogenerated R files
    	System.out.println("Kappa = "+ gp.getKappa());
    	vSeries = getPotential();
    	psiSeries = getData();
    	GraphView graphView = new LineGraphView(  
    			this, // context  
    			"T: "+formatter.format(Transmitted)+
    			"     R: "+formatter.format(Reflected)  //Format the decimals to *.*** format.
    			); 
    	((LineGraphView) graphView).setDrawBackground(true);
    	graphView.addSeries(psiSeries); // Add Psi data
    	graphView.addSeries(vSeries);   // Add V(x) data
        
        
     // set view port, start=-5, size=10  optional stuff
        //graphView.setViewPort(-5, 10);
        graphView.setScrollable(false);  
        // optional - activate scaling / zooming  
        graphView.setScalable(false); 

        LinearLayout layout = (LinearLayout) findViewById(R.id.llplot);
        layout.removeAllViews();
        layout.addView(graphView);
    }
    
    /**
     * Static function to return GraphViewSeries data of Psi(x)
     * @param gp The gaussianParameter object used here
     * @return series Psi(x) vs. x in the GraphViewSeries format
     */
    public GraphViewSeries getData(){
    	double[] x = gp.getXvals();
    	double[] psi = gp.getRealPsi();
    	GraphViewData[] data = new GraphViewData[x.length];
    	for(int i=0; i<x.length; i++){
    		data [i] = new GraphViewData(x[i], psi[i]);
    	}
    	GraphViewSeries series = new GraphViewSeries("Psi", null, data);
    	return series;
    	}
    /**
     * Static function to return GraphViewSeries data of V(x)
     * @param gp The gaussianParameter object used here
     * @return series V(x) vs. x in the GraphViewSeries format
     */
    public GraphViewSeries getPotential(){
    	double alph = gp.getAlpha();
    	double[] x = gp.getXvals();
    	double[] V = new double[x.length];
    	for(int i = 0; i<x.length; i++){
    		V[i]= gp.van(alph, x[i]);
    	}
    	GraphViewData[] data = new GraphViewData[x.length];
    	for(int j=0; j<x.length; j++){
    		data [j] = new GraphViewData(x[j], V[j]);
    	}
    	GraphViewSeries series = new GraphViewSeries("V(x)", Color.rgb(200, 0, 0), data);
    	return series;
    }
}